<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAtojhgm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAtojhgm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAtojhgm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAtojhgm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAtojhgm\appDevDebugProjectContainer([
    'container.build_hash' => 'Atojhgm',
    'container.build_id' => '655bcf1e',
    'container.build_time' => 1734483131,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAtojhgm');
