<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXu7rsp6\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXu7rsp6/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXu7rsp6.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXu7rsp6\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXu7rsp6\appDevDebugProjectContainer([
    'container.build_hash' => 'Xu7rsp6',
    'container.build_id' => 'f186b533',
    'container.build_time' => 1734514477,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXu7rsp6');
