<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container845ewxl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container845ewxl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container845ewxl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container845ewxl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container845ewxl\appDevDebugProjectContainer([
    'container.build_hash' => '845ewxl',
    'container.build_id' => 'a28af3fb',
    'container.build_time' => 1733777455,
], __DIR__.\DIRECTORY_SEPARATOR.'Container845ewxl');
