services:
  prestashop:
    container_name: prestashop
    image: ghcr.io/piotreuszxx/pg-biznes:latest
    restart: always
    ports:
      - "19333:443"
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_193331
      DB_USER: root
      DB_PASSWD: student
    networks:
      - admin-mysql_default
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

networks:
  admin-mysql_default:
    external: true