services:
  prestashop-simulation:
    container_name: prestashop
    image: ghcr.io/piotreuszxx/pg-biznes:latest
    restart: always
    ports:
      - "19333:443"
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_193331
      DB_USER: root
      DB_PASSWD: student
    networks:
      - prestashop_network
  mysql:
    container_name: admin-mysql_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: BE_193331
    volumes:
      - ../dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - prestashop_network

networks:
    prestashop_network: