<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxsn8m2\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxsn8m2/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDxsn8m2.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDxsn8m2\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDxsn8m2\appDevDebugProjectContainer([
    'container.build_hash' => 'Dxsn8m2',
    'container.build_id' => '0ac620d6',
    'container.build_time' => 1738082267,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxsn8m2');
