<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEdjtyhs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEdjtyhs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEdjtyhs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEdjtyhs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEdjtyhs\appDevDebugProjectContainer([
    'container.build_hash' => 'Edjtyhs',
    'container.build_id' => 'fc35d662',
    'container.build_time' => 1738017429,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEdjtyhs');
