<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUkuvitl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUkuvitl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUkuvitl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUkuvitl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUkuvitl\appDevDebugProjectContainer([
    'container.build_hash' => 'Ukuvitl',
    'container.build_id' => '3b897bed',
    'container.build_time' => 1738025090,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUkuvitl');
