<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCx15vn9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCx15vn9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCx15vn9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCx15vn9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCx15vn9\appProdProjectContainer([
    'container.build_hash' => 'Cx15vn9',
    'container.build_id' => 'b92e385e',
    'container.build_time' => 1733777413,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCx15vn9');
