services:
  prestashop:
    image: prestashop/prestashop:1.7.8
    ports:
      - "8080:80"
    environment:
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=prestashop_user
      - DB_PASSWORD=qwerty123456
      - PS_DEV_MODE=true
    depends_on:
      - db
    volumes:
      - ../prestashop_monorepo/front:/var/www/html # Bind to local directory

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty123456
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop_user
      - MYSQL_PASSWORD=qwerty123456
    volumes:
      - ../prestashop_monorepo/back:/var/lib/mysql

volumes:
  prestashop_data:
    driver: local
  db_data:
    driver: local
