<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEventbus\Provider\TranslationDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Provider\\TranslationDataProvider'] = new \PrestaShop\Module\PsEventbus\Provider\TranslationDataProvider(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\TranslationRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\TranslationRepository'] : $this->load('getTranslationRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\TranslationDecorator']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\TranslationDecorator'] : ($this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\TranslationDecorator'] = new \PrestaShop\Module\PsEventbus\Decorator\TranslationDecorator())) && false ?: '_'});
