<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEventbus\Provider\EmployeeDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Provider\\EmployeeDataProvider'] = new \PrestaShop\Module\PsEventbus\Provider\EmployeeDataProvider(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\EmployeeRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\EmployeeRepository'] : $this->load('getEmployeeRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\EmployeeDecorator']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\EmployeeDecorator'] : ($this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\EmployeeDecorator'] = new \PrestaShop\Module\PsEventbus\Decorator\EmployeeDecorator())) && false ?: '_'});
