<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxrxrvn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxrxrvn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOxrxrvn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOxrxrvn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOxrxrvn\appDevDebugProjectContainer([
    'container.build_hash' => 'Oxrxrvn',
    'container.build_id' => '0db48ae4',
    'container.build_time' => 1734513882,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxrxrvn');
