<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5bnbsap\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5bnbsap/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5bnbsap.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5bnbsap\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5bnbsap\appDevDebugProjectContainer([
    'container.build_hash' => '5bnbsap',
    'container.build_id' => '46a9b035',
    'container.build_time' => 1734290842,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5bnbsap');
